version: '3'
services:
  drools-workbench:
    container_name: drools-workbench
    image: jboss/drools-workbench-showcase:latest
    ports:
      - "8080:8080"

  kie-server:
    container_name: kie-server
    image: quay.io/kiegroup/kie-server-showcase:latest
    ports:
      - "8180:8080"
    links:
      - "drools-workbench:kie-wb"
    depends_on:
      - drools-workbench
