server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: /orchestrator/v1
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}

  pattern:
    console: "[%thread][%highlight(%-5level)][%cyan(%d{yyyy-MM-dd HH:mm:ss})][%yellow(%X{requestId})][%magenta(%logger{40})] - %msg%n"

spring:
  application:
    name: api-orchestrator
  main:
    allow-bean-definition-overriding: true
  devtools:
    add-properties: ${SPRING_DEV_TOOLS:true}
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:local}

#Gateway
rest:
  api:
      drools-server:
        uri: ${REST_API_URI_DROOLS_SERVER:http://localhost:8180/kie-server/services/rest/server}
        username: admin
        password: admin
